### PR TITLE
#15 - Tip to angularjs $scope.on() and $rootScope.on()

### PR DESCRIPTION
**Pull request by xiaoyu5256**
If we use `$state.reload()` by angular-ui's UI-Router,we will find that,`$rootScope.on()` will trigger many times;

### CODE REVIEW

**Comment by xcatliu** [comment]
Hi @xiaoyu5256 
The official jstips repo is https://github.com/loverajoel/jstips, perhaps you should create a pull request to that repo.

**Comment by xiaoyu5256** [comment]
thanks @xcatliu,can you close it?

**Comment by xiaoyu5256** [comment]
@xcatliu  看资料才发现，原来是美团的，呵呵,都是中国人

**Comment by xcatliu** [comment]
@xiaoyu5256 😀

**Pull request closed without merging**
